notifications:
  email: false

language: python
os: linux
dist: xenial

jobs:
  include:
    - stage: build
      name: "Linux wheels building"
      services:
        - docker
      language: python
      python: "3.7"
      env:
        - CIBW_SKIP="cp27-* cp33-* cp34-* cp35-* *win* *i686*"
        - CIBW_MANYLINUX_X86_64_IMAGE=manylinux2014
        - CIBW_MANYLINUX_I686_IMAGE=manylinux2014
        - CIBW_BEFORE_BUILD="pip install -r requirements.txt"
      before_install:
        - sudo apt-get update && sudo apt-get install -y libogg-dev libopus-dev ca-certificates libopusfile-dev build-essential
#
#    - name: "macOS wheels building"
#      os: osx
#      osx_image: xcode11.2
#      language: shell
#      compiler: clang
#      env:
#        - MACOSX_DEPLOYMENT_TARGET=10.14
#        - CIBW_SKIP="cp27-* cp33-* cp34-* *win* *i686*"
#        - CIBW_MANYLINUX_X86_64_IMAGE=manylinux2010
#        - CIBW_BEFORE_BUILD="pip install -r requirements.txt"
#        - CXX="g++"
#        - CC="gcc"
#      before_install:
#        - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
#        - python3 get-pip.py

install:
  - pip install -U pip
  - pip install cibuildwheel==1.1.0 twine==1.15.0
  - pip install -r requirements.txt

script:
  - cibuildwheel --output-dir wheelhouse
  - ls -l wheelhouse
  - |
    if [[ $TRAVIS_TAG ]]; then
      rm -rf dist && python setup.py sdist
      twine upload -u __token__ -p $PYPI_TOKEN --skip-existing dist/*.tar.gz wheelhouse/*.whl
    fi
